# Generated by Django 5.1.6 on 2025-03-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_cost_image_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='image',
            name='distance',
        ),
    ]
